BEGIN;
CREATE SCHEMA IF NOT EXISTS nexus;
ALTER TABLE nexus.blockchain_nodes
 ADD COLUMN IF NOT EXISTS node_id TEXT,
 ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT '',
 ADD COLUMN IF NOT EXISTS coin TEXT NOT NULL DEFAULT '',
 ADD COLUMN IF NOT EXISTS chain TEXT NOT NULL DEFAULT '',
 ADD COLUMN IF NOT EXISTS host TEXT NOT NULL DEFAULT '',
 ADD COLUMN IF NOT EXISTS ip_address TEXT NOT NULL DEFAULT '',
 ADD COLUMN IF NOT EXISTS rpc_port INTEGER,
 ADD COLUMN IF NOT EXISTS p2p_port INTEGER,
 ADD COLUMN IF NOT EXISTS rpc_connected BOOLEAN NOT NULL DEFAULT FALSE,
 ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'unknown',
 ADD COLUMN IF NOT EXISTS version TEXT NOT NULL DEFAULT '',
 ADD COLUMN IF NOT EXISTS block_height BIGINT,
 ADD COLUMN IF NOT EXISTS header_height BIGINT,
 ADD COLUMN IF NOT EXISTS sync_percent DOUBLE PRECISION,
 ADD COLUMN IF NOT EXISTS peer_count INTEGER,
 ADD COLUMN IF NOT EXISTS mempool_transactions BIGINT,
 ADD COLUMN IF NOT EXISTS disk_usage_bytes BIGINT,
 ADD COLUMN IF NOT EXISTS first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ,
 ADD COLUMN IF NOT EXISTS last_changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 ADD COLUMN IF NOT EXISTS raw_payload JSONB NOT NULL DEFAULT '{}'::JSONB,
 ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
UPDATE nexus.blockchain_nodes SET node_id=COALESCE(NULLIF(node_id,''),'blockchain-node-'||md5(COALESCE(name,'')||':'||COALESCE(ip_address,'')||':'||COALESCE(host,''))) WHERE node_id IS NULL OR node_id='';
ALTER TABLE nexus.blockchain_nodes ALTER COLUMN node_id SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_blockchain_nodes_node_id ON nexus.blockchain_nodes(node_id);
ALTER TABLE nexus.miningcore_instances
 ADD COLUMN IF NOT EXISTS instance_id TEXT,
 ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT '',
 ADD COLUMN IF NOT EXISTS endpoint TEXT NOT NULL DEFAULT '',
 ADD COLUMN IF NOT EXISTS host TEXT NOT NULL DEFAULT '',
 ADD COLUMN IF NOT EXISTS port INTEGER,
 ADD COLUMN IF NOT EXISTS connected BOOLEAN NOT NULL DEFAULT FALSE,
 ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'unknown',
 ADD COLUMN IF NOT EXISTS health TEXT NOT NULL DEFAULT 'unknown',
 ADD COLUMN IF NOT EXISTS version TEXT NOT NULL DEFAULT '',
 ADD COLUMN IF NOT EXISTS pool_count INTEGER NOT NULL DEFAULT 0,
 ADD COLUMN IF NOT EXISTS first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ,
 ADD COLUMN IF NOT EXISTS last_changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 ADD COLUMN IF NOT EXISTS raw_payload JSONB NOT NULL DEFAULT '{}'::JSONB,
 ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
UPDATE nexus.miningcore_instances SET instance_id=COALESCE(NULLIF(instance_id,''),'miningcore-'||md5(COALESCE(endpoint,'')||':'||COALESCE(host,'')||':'||COALESCE(name,''))) WHERE instance_id IS NULL OR instance_id='';
ALTER TABLE nexus.miningcore_instances ALTER COLUMN instance_id SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_miningcore_instances_instance_id ON nexus.miningcore_instances(instance_id);
INSERT INTO public.schema_migrations(version,description) VALUES('006','Persist blockchain nodes and MiningCore instances') ON CONFLICT(version) DO NOTHING;
COMMIT;
